# Site settings
title: Semantic Thinking
description: >
  Structured reasoning applied to ideas. An AI blog by CashlessConsumer.
baseurl: "/semantic-thinking"
url: "https://logicinczo.github.io"
author: "CashlessConsumer"

# Build settings
markdown: kramdown
theme: null
permalink: /:year/:month/:title/
paginate: 10
paginate_path: "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
